apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: simple-nodejs-app-zpbp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: simple-nodejs-app-zpbp
    app.kubernetes.io/part-of: nodejs-users
  name: simple-nodejs-app-zpbp
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: simple-nodejs-app-zpbp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: simple-nodejs-app-zpbp
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/e2e-demos-ihls-tenant/nodejs-users/simple-nodejs-app-zpbp@sha256:f974f4c89fb6c5a07086fb001734e4b0e3d415d95ed09c41d05e33480d788a76
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
